const hotels = [
  {
    id: 1,
    name: "Grand Plaza Hotel",
    location: "New York City, NY",
    price: 299,
    rating: 4.8,
    image:
      "https://plus.unsplash.com/premium  _photo-1661963123153-5471a95b7042?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGdyYW5kJTIwcGxhemElMjBob3RlbHxlbnwwfHwwfHx8MA%3D%3D",
    images: [
      "https://plus.unsplash.com/premium_photo-1661963123153-5471a95b7042?w=600&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1653280675477-878425ecb5f9?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGdyYW5kcGxhemElMjBob3RlbHxlbnwwfHwwfHx8MA%3D%3D",
      "https://plus.unsplash.com/premium_photo-1674651240687-92b4ad15d0ea?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fGdyYW5kcGxhemElMjBob3RlbHxlbnwwfHwwfHx8MA%3D%3D",
    ],
    amenities: ["Free WiFi", "Pool", "Spa", "Gym", "Restaurant"],
    description:
      "Experience luxury in the heart of Manhattan with stunning city views and world-class service.",
    duration: "1 night",
    people: "2 adults",
    geolocation: {
      latitude: 40.758,
      longitude: -73.9855,
    },
    roomTypes: [
      { type: "Standard", price: 279, total: 10 },
      { type: "Deluxe", price: 209, total: 10 },
      { type: "Suite", price: 349, total: 9 },
    ],
    bookingstatus: [
      // Standard Rooms
      {
        bookingId: "b001",
        roomId: "std1001",
        roomType: "Standard",
        userId: "u001",
        email: "alice@example.com",
        phone: "+11234567890",
        checkIn: "2025-06-18",
        checkOut: "2025-06-20",
      },
      {
        bookingId: "",
        roomId: "std1002",
        roomType: "Standard",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "b002",
        roomId: "std1003",
        roomType: "Standard", 
        userId: "u002",
        email: "bob@example.com", 
        phone: "+11234567891",
        checkIn: "2025-06-19",
        checkOut: "2025-06-22",
      },
      {
        bookingId: "",
        roomId: "std1004",
        roomType: "Standard",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "b003",
        roomId: "std1005",
        roomType: "Standard",
        userId: "u003",
        email: "carla@example.com",
        phone: "+11234567892",
        checkIn: "2025-06-21",
        checkOut: "2025-06-23",
      },
      {
        bookingId: "b004",
        roomId: "std1006",
        roomType: "Standard",
        userId: "u004",
        email: "dave@example.com",
        phone: "+11234567893",
        checkIn: "2025-06-18",
        checkOut: "2025-06-19",
      },
      {
        bookingId: "",
        roomId: "std1007",
        roomType: "Standard",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "b005",
        roomId: "std1008",
        roomType: "Standard",
        userId: "u005",
        email: "emma@example.com",
        phone: "+11234567894",
        checkIn: "2025-06-20",
        checkOut: "2025-06-22",
      },
      {
        bookingId: "",
        roomId: "std1009",
        roomType: "Standard",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "",
        roomId: "std1010",
        roomType: "Standard",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },

      // Deluxe Rooms
      {
        bookingId: "b006",
        roomId: "del2001",
        roomType: "Deluxe",
        userId: "u006",
        email: "frank@example.com",
        phone: "+11234567895",
        checkIn: "2025-06-17",
        checkOut: "2025-06-18",
      },
      {
        bookingId: "",
        roomId: "del2002",
        roomType: "Deluxe",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "b007",
        roomId: "del2003",
        roomType: "Deluxe",
        userId: "u007",
        email: "grace@example.com",
        phone: "+11234567896",
        checkIn: "2025-06-20",
        checkOut: "2025-06-23",
      },
      {
        bookingId: "b008",
        roomId: "del2004",
        roomType: "Deluxe",
        userId: "u008",
        email: "harry@example.com",
        phone: "+11234567897",
        checkIn: "2025-06-18",
        checkOut: "2025-06-19",
      },
      {
        bookingId: "",
        roomId: "del2005",
        roomType: "Deluxe",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "",
        roomId: "del2006",
        roomType: "Deluxe",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "b009",
        roomId: "del2007",
        roomType: "Deluxe",
        userId: "u009",
        email: "isla@example.com",
        phone: "+11234567898",
        checkIn: "2025-06-19",
        checkOut: "2025-06-21",
      },
      {
        bookingId: "",
        roomId: "del2008",
        roomType: "Deluxe",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "b010",
        roomId: "del2009",
        roomType: "Deluxe",
        userId: "u010",
        email: "jack@example.com",
        phone: "+11234567899",
        checkIn: "2025-06-18",
        checkOut: "2025-06-20",
      },
      {
        bookingId: "",
        roomId: "del2010",
        roomType: "Deluxe",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },

      // Suite Rooms
      {
        bookingId: "",
        roomId: "sui3001",
        roomType: "Suite",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "b011",
        roomId: "sui3002",
        roomType: "Suite",
        userId: "u011",
        email: "kate@example.com",
        phone: "+11234567900",
        checkIn: "2025-06-19",
        checkOut: "2025-06-21",
      },
      {
        bookingId: "",
        roomId: "sui3003",
        roomType: "Suite",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "b012",
        roomId: "sui3004",
        roomType: "Suite",
        userId: "u012",
        email: "leo@example.com",
        phone: "+11234567901",
        checkIn: "2025-06-20",
        checkOut: "2025-06-23",
      },
      {
        bookingId: "",
        roomId: "sui3005",
        roomType: "Suite",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "",
        roomId: "sui3006",
        roomType: "Suite",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "b013",
        roomId: "sui3007",
        roomType: "Suite",
        userId: "u013",
        email: "mia@example.com",
        phone: "+11234567902",
        checkIn: "2025-06-21",
        checkOut: "2025-06-24",
      },
      {
        bookingId: "",
        roomId: "sui3008",
        roomType: "Suite",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "",
        roomId: "sui3009",
        roomType: "Suite",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
    ],
    isActive: true,
  },
  {
    id: 2,
    name: "Oceanview Resort",
    location: "Miami Beach, FL",
    price: 349,
    rating: 4.7,
    image:
      "https://images.unsplash.com/photo-1646598446711-e320fe4af62e?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8b2NlYW4lMjB2aWV3JTIwcmVzb3J0fGVufDB8fDB8fHww",
    images: [
      "https://images.unsplash.com/photo-1646598446711-e320fe4af62e?w=600",
      "https://images.unsplash.com/photo-1576678927489-4b1aa6c3ab9b?w=600",
      "https://images.unsplash.com/photo-1600585154505-9808f73bd1c7?w=600",
    ],
    amenities: ["Beachfront", "Pool", "Spa", "Free Breakfast", "Bar"],
    description:
      "Beachfront paradise with private balconies and direct access to pristine white sand beaches.",
    duration: "1 night",
    people: "2 adults",
    geolocation: {
      latitude: 25.7932,
      longitude: -80.1306,
    },
    roomTypes: [
      { type: "Standard", price: 299, total: 12 },
      { type: "Deluxe", price: 399, total: 8 },
      { type: "Suite", price: 499, total: 6 },
    ],
    bookingstatus: [
      // Standard Rooms
      {
        bookingId: "b201",
        roomId: "std2001",
        roomType: "Standard",
        userId: "u201",
        email: "nina@example.com",
        phone: "+11230000001",
        checkIn: "2025-06-18",
        checkOut: "2025-06-20",
      },
      {
        bookingId: "",
        roomId: "std2002",
        roomType: "Standard",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "b202",
        roomId: "std2003",
        roomType: "Standard",
        userId: "u202",
        email: "oliver@example.com",
        phone: "+11230000002",
        checkIn: "2025-06-17",
        checkOut: "2025-06-19",
      },
      {
        bookingId: "",
        roomId: "std2004",
        roomType: "Standard",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "b203",
        roomId: "std2005",
        roomType: "Standard",
        userId: "u203",
        email: "paula@example.com",
        phone: "+11230000003",
        checkIn: "2025-06-19",
        checkOut: "2025-06-22",
      },
      {
        bookingId: "b204",
        roomId: "std2006",
        roomType: "Standard",
        userId: "u204",
        email: "quinn@example.com",
        phone: "+11230000004",
        checkIn: "2025-06-20",
        checkOut: "2025-06-21",
      },
      {
        bookingId: "",
        roomId: "std2007",
        roomType: "Standard",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "b205",
        roomId: "std2008",
        roomType: "Standard",
        userId: "u205",
        email: "ryan@example.com",
        phone: "+11230000005",
        checkIn: "2025-06-18",
        checkOut: "2025-06-20",
      },
      {
        bookingId: "",
        roomId: "std2009",
        roomType: "Standard",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "",
        roomId: "std2010",
        roomType: "Standard",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "b206",
        roomId: "std2011",
        roomType: "Standard",
        userId: "u206",
        email: "sara@example.com",
        phone: "+11230000006",
        checkIn: "2025-06-21",
        checkOut: "2025-06-23",
      },
      {
        bookingId: "",
        roomId: "std2012",
        roomType: "Standard",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },

      // Deluxe Rooms
      {
        bookingId: "b207",
        roomId: "del3001",
        roomType: "Deluxe",
        userId: "u207",
        email: "tina@example.com",
        phone: "+11230000007",
        checkIn: "2025-06-18",
        checkOut: "2025-06-19",
      },
      {
        bookingId: "",
        roomId: "del3002",
        roomType: "Deluxe",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "",
        roomId: "del3003",
        roomType: "Deluxe",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "b208",
        roomId: "del3004",
        roomType: "Deluxe",
        userId: "u208",
        email: "umar@example.com",
        phone: "+11230000008",
        checkIn: "2025-06-17",
        checkOut: "2025-06-18",
      },
      {
        bookingId: "",
        roomId: "del3005",
        roomType: "Deluxe",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "b209",
        roomId: "del3006",
        roomType: "Deluxe",
        userId: "u209",
        email: "vicky@example.com",
        phone: "+11230000009",
        checkIn: "2025-06-19",
        checkOut: "2025-06-22",
      },
      {
        bookingId: "",
        roomId: "del3007",
        roomType: "Deluxe",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "b210",
        roomId: "del3008",
        roomType: "Deluxe",
        userId: "u210",
        email: "will@example.com",
        phone: "+11230000010",
        checkIn: "2025-06-20",
        checkOut: "2025-06-21",
      },

      // Suite Rooms
      {
        bookingId: "b211",
        roomId: "sui4001",
        roomType: "Suite",
        userId: "u211",
        email: "xena@example.com",
        phone: "+11230000011",
        checkIn: "2025-06-18",
        checkOut: "2025-06-20",
      },
      {
        bookingId: "",
        roomId: "sui4002",
        roomType: "Suite",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "",
        roomId: "sui4003",
        roomType: "Suite",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "b212",
        roomId: "sui4004",
        roomType: "Suite",
        userId: "u212",
        email: "yasmin@example.com",
        phone: "+11230000012",
        checkIn: "2025-06-19",
        checkOut: "2025-06-21",
      },
      {
        bookingId: "b213",
        roomId: "sui4005",
        roomType: "Suite",
        userId: "u213",
        email: "zack@example.com",
        phone: "+11230000013",
        checkIn: "2025-06-20",
        checkOut: "2025-06-22",
      },
      {
        bookingId: "",
        roomId: "sui4006",
        roomType: "Suite",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
    ],
    isActive: true,
  },
  {
    id: 3,
    name: "Mountain Lodge",
    location: "Aspen, CO",
    price: 279,
    rating: 4.6,
    image:
      "https://images.unsplash.com/photo-1621765663900-f132db309fda?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    images: [
      "https://images.unsplash.com/photo-1621765663900-f132db309fda?q=80&w=600",
      "https://images.unsplash.com/photo-1621765663900-f132db309fda?q=80&w=600",
      "https://images.unsplash.com/photo-1621765663900-f132db309fda?q=80&w=600",
    ],
    amenities: ["Fireplace", "Ski-in/Ski-out", "Hot Tub", "Restaurant", "Bar"],
    description:
      "Cozy mountain retreat with ski-in/ski-out access and breathtaking alpine views.",
    duration: "1 night",
    people: "2 adults",
    geolocation: {
      latitude: 39.1911,
      longitude: -106.8175,
    },
    roomTypes: [
      { type: "Standard", price: 249, total: 8 },
      { type: "Deluxe", price: 329, total: 6 },
      { type: "Suite", price: 429, total: 4 },
    ],

    bookingstatus: [
      // Standard Rooms
      {
        bookingId: "b301",
        roomId: "std3001",
        roomType: "Standard",
        userId: "u301",
        email: "alice@example.com",
        phone: "+11234000001",
        checkIn: "2025-06-18",
        checkOut: "2025-06-19",
      },
      {
        bookingId: "",
        roomId: "std3002",
        roomType: "Standard",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "b302",
        roomId: "std3003",
        roomType: "Standard",
        userId: "u302",
        email: "bob@example.com",
        phone: "+11234000002",
        checkIn: "2025-06-17",
        checkOut: "2025-06-20",
      },
      {
        bookingId: "",
        roomId: "std3004",
        roomType: "Standard",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "b303",
        roomId: "std3005",
        roomType: "Standard",
        userId: "u303",
        email: "carla@example.com",
        phone: "+11234000003",
        checkIn: "2025-06-19",
        checkOut: "2025-06-22",
      },
      {
        bookingId: "",
        roomId: "std3006",
        roomType: "Standard",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "b304",
        roomId: "std3007",
        roomType: "Standard",
        userId: "u304",
        email: "david@example.com",
        phone: "+11234000004",
        checkIn: "2025-06-18",
        checkOut: "2025-06-21",
      },
      {
        bookingId: "",
        roomId: "std3008",
        roomType: "Standard",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },

      // Deluxe Rooms
      {
        bookingId: "b305",
        roomId: "del4001",
        roomType: "Deluxe",
        userId: "u305",
        email: "emma@example.com",
        phone: "+11234000005",
        checkIn: "2025-06-18",
        checkOut: "2025-06-19",
      },
      {
        bookingId: "",
        roomId: "del4002",
        roomType: "Deluxe",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "",
        roomId: "del4003",
        roomType: "Deluxe",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "b306",
        roomId: "del4004",
        roomType: "Deluxe",
        userId: "u306",
        email: "frank@example.com",
        phone: "+11234000006",
        checkIn: "2025-06-20",
        checkOut: "2025-06-22",
      },
      {
        bookingId: "",
        roomId: "del4005",
        roomType: "Deluxe",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "b307",
        roomId: "del4006",
        roomType: "Deluxe",
        userId: "u307",
        email: "grace@example.com",
        phone: "+11234000007",
        checkIn: "2025-06-21",
        checkOut: "2025-06-23",
      },

      // Suite Rooms
      {
        bookingId: "b308",
        roomId: "sui5001",
        roomType: "Suite",
        userId: "u308",
        email: "hank@example.com",
        phone: "+11234000008",
        checkIn: "2025-06-18",
        checkOut: "2025-06-20",
      },
      {
        bookingId: "",
        roomId: "sui5002",
        roomType: "Suite",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
      {
        bookingId: "b309",
        roomId: "sui5003",
        roomType: "Suite",
        userId: "u309",
        email: "irene@example.com",
        phone: "+11234000009",
        checkIn: "2025-06-19",
        checkOut: "2025-06-21",
      },
      {
        bookingId: "",
        roomId: "sui5004",
        roomType: "Suite",
        userId: "",
        email: "",
        phone: "",
        checkIn: "",
        checkOut: "",
      },
    ],

    isActive: true,
  },
];

module.exports = hotels;
